name: Build and Deploy

on:
  push:
    branches:
    - main
  schedule:
  - cron: '0 */2 * * *'
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v5
      with:
        node-version: 22
    - id: date
      run: echo "::set-output name=today::$(date +'%Y-%m-%d')"
    - uses: actions/cache@v4
      with:
        path: .cache
        key: betor-cache-${{ steps.date.outputs.today }}
    - run: npm ci
    - run: npm link
    - env:
        TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
      run: betor-catalog -b ${{ vars.BETOR_API_URL }} -a ${{ secrets.BETOR_API_AUTHORIZATION }} build-items
    - run: betor-catalog build
    - run: cp src/_data/*.json dist/static/data
    - run: npm install surge
    - run: npx surge dist ${{ vars.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
    - uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  purge-cache:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
    - uses: jakejarvis/cloudflare-purge-action@master
      env:
        CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
